import Head from "next/head";

// import { PROJECT_NAME } from "../../config";
import { Header } from "./Header";

const Layout = ({ children }: { children: any }) => {
  return (
    <div data-theme className="bg-cover bg-center bg-[#FFEAF1]">
      <Head>
        <title>{`Onboarding Frens`}</title>
        <meta name="description" content="Generated by create-teddy-bear" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>

      <div className="h-screen">
        <Header />
        {children}
      </div>
    </div>
  );
};

export default Layout;
